spring.application.name=RentVideo

# MySQL connection settings
spring.datasource.url=jdbc:mysql://localhost:3306/rent_video?useSSL=false&serverTimezone=UTC
spring.datasource.username=admin24
spring.datasource.password=admin234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings: update DB schema automatically
spring.jpa.hibernate.ddl-auto=update

# Disable Spring Boot's automatic execution of data.sql to avoid errors on startup
spring.sql.init.mode=always

# Show SQL statements in logs (optional, useful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Use Hibernate dialect for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
