INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Inception', 'Christopher Nolan', 'Sci-Fi', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Interstellar', 'Christopher Nolan', 'Sci-Fi', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Dark Knight', 'Christopher Nolan', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Tenet', 'Christopher Nolan', 'Thriller', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Memento', 'Christopher Nolan', 'Thriller', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Prestige', 'Christopher Nolan', 'Drama', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Avatar', 'James Cameron', 'Sci-Fi', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Titanic', 'James Cameron', 'Romance', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Aliens', 'James Cameron', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Terminator 2: Judgment Day', 'James Cameron', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Terminator', 'James Cameron', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('True Lies', 'James Cameron', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Pulp Fiction', 'Quentin Tarantino', 'Crime', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Kill Bill: Vol. 1', 'Quentin Tarantino', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Kill Bill: Vol. 2', 'Quentin Tarantino', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Django Unchained', 'Quentin Tarantino', 'Western', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Inglourious Basterds', 'Quentin Tarantino', 'War', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Reservoir Dogs', 'Quentin Tarantino', 'Crime', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Once Upon a Time in Hollywood', 'Quentin Tarantino', 'Drama', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Hateful Eight', 'Quentin Tarantino', 'Western', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Shawshank Redemption', 'Frank Darabont', 'Drama', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Green Mile', 'Frank Darabont', 'Drama', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Mist', 'Frank Darabont', 'Horror', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Godfather', 'Francis Ford Coppola', 'Crime', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Godfather: Part II', 'Francis Ford Coppola', 'Crime', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Godfather: Part III', 'Francis Ford Coppola', 'Crime', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Apocalypse Now', 'Francis Ford Coppola', 'War', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Bram Stoker''s Dracula', 'Francis Ford Coppola', 'Horror', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Goodfellas', 'Martin Scorsese', 'Crime', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Wolf of Wall Street', 'Martin Scorsese', 'Drama', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Shutter Island', 'Martin Scorsese', 'Thriller', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Taxi Driver', 'Martin Scorsese', 'Drama', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Raging Bull', 'Martin Scorsese', 'Drama', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Casino', 'Martin Scorsese', 'Crime', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Avengers: Endgame', 'Anthony Russo, Joe Russo', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Avengers: Infinity War', 'Anthony Russo, Joe Russo', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Captain America: Civil War', 'Anthony Russo, Joe Russo', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Captain America: The Winter Soldier', 'Anthony Russo, Joe Russo', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Community', 'Anthony Russo, Joe Russo', 'Comedy', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Guardians of the Galaxy', 'James Gunn', 'Sci-Fi', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Guardians of the Galaxy Vol. 2', 'James Gunn', 'Sci-Fi', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Suicide Squad', 'James Gunn', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Peacemaker', 'James Gunn', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Jurassic Park', 'Steven Spielberg', 'Adventure', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Jurassic World', 'Colin Trevorrow', 'Adventure', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('E.T. the Extra-Terrestrial', 'Steven Spielberg', 'Sci-Fi', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Jaws', 'Steven Spielberg', 'Thriller', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Saving Private Ryan', 'Steven Spielberg', 'War', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Schindler''s List', 'Steven Spielberg', 'Drama', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Ready Player One', 'Steven Spielberg', 'Sci-Fi', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Minority Report', 'Steven Spielberg', 'Sci-Fi', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Catch Me If You Can', 'Steven Spielberg', 'Crime', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('War Horse', 'Steven Spielberg', 'War', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Lincoln', 'Steven Spielberg', 'Drama', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Hook', 'Steven Spielberg', 'Fantasy', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Fabelmans', 'Steven Spielberg', 'Drama', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Back to the Future', 'Robert Zemeckis', 'Sci-Fi', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Forrest Gump', 'Robert Zemeckis', 'Drama', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Cast Away', 'Robert Zemeckis', 'Drama', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Polar Express', 'Robert Zemeckis', 'Animation', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Flight', 'Robert Zemeckis', 'Drama', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Contact', 'Robert Zemeckis', 'Sci-Fi', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Who Framed Roger Rabbit', 'Robert Zemeckis', 'Comedy', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Beowulf', 'Robert Zemeckis', 'Fantasy', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Deadpool', 'Tim Miller', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Deadpool 2', 'David Leitch', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('John Wick', 'Chad Stahelski', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('John Wick: Chapter 2', 'Chad Stahelski', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('John Wick: Chapter 3 – Parabellum', 'Chad Stahelski', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('John Wick: Chapter 4', 'Chad Stahelski', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Mad Max: Fury Road', 'George Miller', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Fury', 'David Ayer', 'War', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Suicide Squad', 'David Ayer', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Bright', 'David Ayer', 'Fantasy', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Training Day', 'Antoine Fuqua', 'Crime', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Equalizer', 'Antoine Fuqua', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Equalizer 2', 'Antoine Fuqua', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Olympus Has Fallen', 'Antoine Fuqua', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('King Arthur', 'Antoine Fuqua', 'Adventure', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Magnificent Seven', 'Antoine Fuqua', 'Western', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Southpaw', 'Antoine Fuqua', 'Drama', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Matrix', 'Lana Wachowski, Lilly Wachowski', 'Sci-Fi', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Matrix Reloaded', 'Lana Wachowski, Lilly Wachowski', 'Sci-Fi', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Matrix Revolutions', 'Lana Wachowski, Lilly Wachowski', 'Sci-Fi', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Matrix Resurrections', 'Lana Wachowski', 'Sci-Fi', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Cloud Atlas', 'Lana Wachowski, Lilly Wachowski', 'Sci-Fi', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Speed Racer', 'Lana Wachowski, Lilly Wachowski', 'Action', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('V for Vendetta', 'James McTeigue', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Ninja Assassin', 'James McTeigue', 'Action', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Imitation Game', 'Morten Tyldum', 'Drama', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Passengers', 'Morten Tyldum', 'Sci-Fi', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Headhunters', 'Morten Tyldum', 'Thriller', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Spotlight', 'Tom McCarthy', 'Drama', 1);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('Stillwater', 'Tom McCarthy', 'Drama', 0);
INSERT IGNORE INTO videos (title, director, genre, is_available) VALUES ('The Station Agent', 'Tom McCarthy', 'Drama', 1);